### PR TITLE
DEVSOL-757: Implement new Security resource

### PR DESCRIPTION
**Pull request by ossobuffo**
This is a re-working of Sudheesh's work on the Security resource. Note that there is still need for modeling the TemplateAuth resource.

### CODE REVIEW

**Comment by cnovak** [comment]
This change needs to be put in the 1.1.x branch, unless you want OPDK versions < 4.15.01 to get this change.

**Comment by ossobuffo** [comment]
I added a cast-to-object on "scopes" in the Oauth2Scheme constructor. When doing an update (PUT), there are also some fields which must be removed from the payload; I've delegated this task to the SecurityScheme subclasses themselves, so if we add more schemes in the future we won't have to hack in more exceptions.

**Comment by sdamodaran** [comment]
Its working fine now. Merging

**Comment by sdamodaran** [comment]
Well as @cnovak pointed out, should this go to the 1.1.x branch ?

**Comment by ossobuffo** [comment]
You're right. I wonder if there's any way to change which branch a PR is destined for.

**Comment by sdamodaran** [comment]
I think we might need to create a new PR

**Comment by ossobuffo** [comment]
This PR is superseded by PR #10.

**Pull request closed without merging**
