### PR TITLE
Security check for PHP libraries

### PR DESCRIPTION
**Pull request by cnovak**
Apigee security asked how we are checking for known vulnerabilities in the libraries we depend on, added hooks to run sensiolabs/security-checker on installs and updates

### CODE REVIEW

**Comment by cnovak** [comment]
Looks like there is more to do to get this working with TravisCI: https://github.com/travis-ci/travis-ci/issues/6339#issuecomment-355158125

**Comment by mxr576** [comment]
I though about adding `sensiolabs/security-checker` to this library but then I realized that this is a library not a project, therefore the developer of the consumer app should check whether its app's dependencies (including this one and its dependencies) are up to date or not.
`sensiolabs/security-checker` could be maximum a dev dependency instead of a mandatory dependency of this library but based on the above reasoning I am giving a -1 for this pull request.

**Comment by mxr576** [comment]
PS.: `A security checker for your composer.lock`  we do not ship composer.lock with our library, we rather do highest-lowest testing to ensure that our library is compatible with the minimum and the latest version of its dependencies.

**Comment by cnovak** [comment]
Yes, the security check should be a dev dependency, made that change. @mxr576 do you have another solution for checking for known vulnerabilities?  We need to be alerted if an issue arises.

**Comment by mxr576** [comment]
@cnovak I can not image what security issues we could possible check in our dependencies if we are not depending on *exact versions* of the libraries we use. (Because basically this is what composer.lock describes in case of PHP project.) Our library just says please install the latest version or at least x.x.0 from the listed packages, in case of `"symfony/serializer": "^3.2 || ^4.0"` it means symfony/serializer >= 3.2.0 or >= 4.0.0.
As I mentioned the consumer app should check whether its dependencies (and dependencies of dependencies) defined in its composer.lock contains any know vulnerabilities or not.

**Comment by mxr576** [comment]
Or do you want to keep tabs on minimum versions that our PHP library requires and ensures that those do not contain any known security risks - in other words, monitor new releases day by day of this library's dependencies and increase the minimum version in this library's composer.json? That would be a huge overhead...

**Comment by cnovak** [comment]
If we don't have PRs often then yes, we would not know about vulnerabilities until the CI ran again.  I am asking our security team for guidance.

**Comment by mxr576** [comment]
https://blog.martinhujer.cz/17-tips-for-using-composer-efficiently/ Tip #5 and #6: About why we should not ship composer.lock in this library - consequently `sensiolabs/security-checker` does not work for us - also we are not depending any secure or insecure dependency directly. The consuming application decides which versions are being installed from its dependencies.

**Pull request closed without merging**
