### PR TITLE
This fixes commit 0f89273: remove left behind code.

### PR DESCRIPTION
**Pull request by dzadza**
This code is wrapped in an if statement just after the deletion.

### CODE REVIEW

**Comment by dzadza** [comment]
I signed it!

**Comment by cnovak** [comment]
@dzadza can you check out the @googlebot CLA issue above so I can approve?  Thanks

**Comment by dzadza** [comment]
@cnovak looks like it's ok now.

**Review by cnovak — APPROVED** [review]
LGTM

**Pull request merged**
